-- ===================================================================
-- SMARTMOVE - ORACLE TEST DATA INSERTION SCRIPT
-- ===================================================================

-- Disable foreign key constraints temporarily if needed, but since we insert in order, it should be fine.

-- 1. PASSENGER TEST DATA
INSERT INTO PASSENGER (PASSENGER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, PASSWORD_HASH, STATUS, ROLE) 
VALUES (1, 'Nimal', 'Perera', 'nimal@example.com', '0771234567', '$2a$10$X', 'ACTIVE', 'PASSENGER');
INSERT INTO PASSENGER (PASSENGER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, PASSWORD_HASH, STATUS, ROLE) 
VALUES (2, 'Sunil', 'Fernando', 'sunil@example.com', '0777654321', '$2a$10$X', 'ACTIVE', 'PASSENGER');
INSERT INTO PASSENGER (PASSENGER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, PASSWORD_HASH, STATUS, ROLE) 
VALUES (3, 'Kamal', 'Silva', 'kamal@example.com', '0712345678', '$2a$10$X', 'ACTIVE', 'PASSENGER');
INSERT INTO PASSENGER (PASSENGER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, PASSWORD_HASH, STATUS, ROLE) 
VALUES (4, 'Amal', 'Bandara', 'amal@example.com', '0788765432', '$2a$10$X', 'INACTIVE', 'PASSENGER');
INSERT INTO PASSENGER (PASSENGER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, PASSWORD_HASH, STATUS, ROLE) 
VALUES (5, 'admin', 'admin', 'admin@smartmove.lk', '0112223334', '$2a$10$X', 'ACTIVE', 'ADMIN');

-- 2. DRIVER TEST DATA
INSERT INTO DRIVER (DRIVER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, LICENSE_NUMBER, PASSWORD_HASH, STATUS, RATING, TOTAL_TRIPS) 
VALUES (1, 'Saman', 'Kumara', 'saman.k@smartmove.lk', '0771122334', 'B1234567', '$2a$10$X', 'ACTIVE', 4.8, 120);
INSERT INTO DRIVER (DRIVER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, LICENSE_NUMBER, PASSWORD_HASH, STATUS, RATING, TOTAL_TRIPS) 
VALUES (2, 'Ruwan', 'Pathirana', 'ruwan.p@smartmove.lk', '0712233445', 'B7654321', '$2a$10$X', 'ON_TRIP', 4.5, 85);
INSERT INTO DRIVER (DRIVER_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE, LICENSE_NUMBER, PASSWORD_HASH, STATUS, RATING, TOTAL_TRIPS) 
VALUES (3, 'Nuwan', 'Jayasinghe', 'nuwan.j@smartmove.lk', '0723344556', 'B9876543', '$2a$10$X', 'ON_LEAVE', 4.9, 210);

-- 3. VEHICLE TEST DATA
INSERT INTO VEHICLE (VEHICLE_ID, REGISTRATION_NUMBER, TYPE, CAPACITY, MODEL, YEAR, STATUS) 
VALUES (1, 'ND-4521', 'Luxury Coach', 45, 'Volvo 9900', 2022, 'ACTIVE');
INSERT INTO VEHICLE (VEHICLE_ID, REGISTRATION_NUMBER, TYPE, CAPACITY, MODEL, YEAR, STATUS) 
VALUES (2, 'ND-3210', 'Mini Bus', 28, 'Toyota Coaster', 2020, 'ACTIVE');
INSERT INTO VEHICLE (VEHICLE_ID, REGISTRATION_NUMBER, TYPE, CAPACITY, MODEL, YEAR, STATUS) 
VALUES (3, 'ND-8891', 'Standard Bus', 54, 'Ashok Leyland', 2019, 'MAINTENANCE');
INSERT INTO VEHICLE (VEHICLE_ID, REGISTRATION_NUMBER, TYPE, CAPACITY, MODEL, YEAR, STATUS) 
VALUES (4, 'ND-1122', 'Luxury Coach', 45, 'Scania Touring', 2023, 'ACTIVE');

-- 4. ROUTE TEST DATA
INSERT INTO ROUTE (ROUTE_ID, ORIGIN, DESTINATION, DISTANCE_KM, ESTIMATED_DURATION, BASE_FARE, STATUS) 
VALUES (1, 'Colombo', 'Kandy', 115.5, '3 Hours', 1500.00, 'ACTIVE');
INSERT INTO ROUTE (ROUTE_ID, ORIGIN, DESTINATION, DISTANCE_KM, ESTIMATED_DURATION, BASE_FARE, STATUS) 
VALUES (2, 'Colombo', 'Galle', 125.0, '2 Hours', 1200.00, 'ACTIVE');
INSERT INTO ROUTE (ROUTE_ID, ORIGIN, DESTINATION, DISTANCE_KM, ESTIMATED_DURATION, BASE_FARE, STATUS) 
VALUES (3, 'Kandy', 'Nuwara Eliya', 75.0, '2.5 Hours', 800.00, 'ACTIVE');
INSERT INTO ROUTE (ROUTE_ID, ORIGIN, DESTINATION, DISTANCE_KM, ESTIMATED_DURATION, BASE_FARE, STATUS) 
VALUES (4, 'Colombo', 'Jaffna', 395.0, '8 Hours', 3500.00, 'ACTIVE');

-- 5. TRIP TEST DATA
INSERT INTO TRIP (TRIP_ID, ROUTE_ID, VEHICLE_ID, DRIVER_ID, DEPARTURE_TIME, ARRIVAL_TIME, AVAILABLE_SEATS, STATUS) 
VALUES (1, 1, 1, 1, TO_TIMESTAMP('2026-10-15 08:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-10-15 11:00:00', 'YYYY-MM-DD HH24:MI:SS'), 40, 'SCHEDULED');
INSERT INTO TRIP (TRIP_ID, ROUTE_ID, VEHICLE_ID, DRIVER_ID, DEPARTURE_TIME, ARRIVAL_TIME, AVAILABLE_SEATS, STATUS) 
VALUES (2, 2, 2, 2, TO_TIMESTAMP('2026-10-10 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-10-10 11:00:00', 'YYYY-MM-DD HH24:MI:SS'), 15, 'IN_PROGRESS');
INSERT INTO TRIP (TRIP_ID, ROUTE_ID, VEHICLE_ID, DRIVER_ID, DEPARTURE_TIME, ARRIVAL_TIME, AVAILABLE_SEATS, STATUS) 
VALUES (3, 3, 4, 1, TO_TIMESTAMP('2026-09-25 07:30:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-09-25 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 0, 'COMPLETED');
INSERT INTO TRIP (TRIP_ID, ROUTE_ID, VEHICLE_ID, DRIVER_ID, DEPARTURE_TIME, ARRIVAL_TIME, AVAILABLE_SEATS, STATUS) 
VALUES (4, 4, 1, 1, TO_TIMESTAMP('2026-10-20 22:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-10-21 06:00:00', 'YYYY-MM-DD HH24:MI:SS'), 45, 'SCHEDULED');

-- 6. BOOKING TEST DATA
INSERT INTO BOOKING (BOOKING_ID, PASSENGER_ID, TRIP_ID, SEATS_BOOKED, TOTAL_FARE, STATUS, PAYMENT_STATUS, BOOKING_DATE) 
VALUES (1, 1, 1, 2, 3000.00, 'CONFIRMED', 'PAID', TO_TIMESTAMP('2026-10-01 14:30:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BOOKING (BOOKING_ID, PASSENGER_ID, TRIP_ID, SEATS_BOOKED, TOTAL_FARE, STATUS, PAYMENT_STATUS, BOOKING_DATE) 
VALUES (2, 2, 2, 1, 1200.00, 'CONFIRMED', 'PAID', TO_TIMESTAMP('2026-10-08 09:15:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BOOKING (BOOKING_ID, PASSENGER_ID, TRIP_ID, SEATS_BOOKED, TOTAL_FARE, STATUS, PAYMENT_STATUS, BOOKING_DATE) 
VALUES (3, 3, 3, 4, 3200.00, 'CONFIRMED', 'PAID', TO_TIMESTAMP('2026-09-20 11:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO BOOKING (BOOKING_ID, PASSENGER_ID, TRIP_ID, SEATS_BOOKED, TOTAL_FARE, STATUS, PAYMENT_STATUS, BOOKING_DATE) 
VALUES (4, 1, 4, 1, 3500.00, 'PENDING', 'UNPAID', TO_TIMESTAMP('2026-10-09 18:45:00', 'YYYY-MM-DD HH24:MI:SS'));

-- 7. PAYMENT TEST DATA
INSERT INTO PAYMENT (PAYMENT_ID, BOOKING_ID, AMOUNT, PAYMENT_METHOD, STATUS, TRANSACTION_REF) 
VALUES (1, 1, 3000.00, 'CREDIT_CARD', 'SUCCESS', 'TXN-9988776655');
INSERT INTO PAYMENT (PAYMENT_ID, BOOKING_ID, AMOUNT, PAYMENT_METHOD, STATUS, TRANSACTION_REF) 
VALUES (2, 2, 1200.00, 'DEBIT_CARD', 'SUCCESS', 'TXN-5544332211');
INSERT INTO PAYMENT (PAYMENT_ID, BOOKING_ID, AMOUNT, PAYMENT_METHOD, STATUS, TRANSACTION_REF) 
VALUES (3, 3, 3200.00, 'BANK_TRANSFER', 'SUCCESS', 'TXN-1122334455');

-- 8. MAINTENANCE TEST DATA
INSERT INTO MAINTENANCE (MAINTENANCE_ID, VEHICLE_ID, DESCRIPTION, COST, MAINTENANCE_DATE, STATUS) 
VALUES (1, 3, 'Engine Oil Replacement and Brake Inspection', 45000.00, TO_DATE('2026-10-08', 'YYYY-MM-DD'), 'IN_PROGRESS');
INSERT INTO MAINTENANCE (MAINTENANCE_ID, VEHICLE_ID, DESCRIPTION, COST, MAINTENANCE_DATE, STATUS) 
VALUES (2, 1, 'Tire Alignment and AC Service', 25000.00, TO_DATE('2026-09-15', 'YYYY-MM-DD'), 'COMPLETED');
INSERT INTO MAINTENANCE (MAINTENANCE_ID, VEHICLE_ID, DESCRIPTION, COST, MAINTENANCE_DATE, STATUS) 
VALUES (3, 2, 'Routine Monthly Checkup', 15000.00, TO_DATE('2026-10-25', 'YYYY-MM-DD'), 'PENDING');

-- 9. FEEDBACK TEST DATA
INSERT INTO FEEDBACK (FEEDBACK_ID, PASSENGER_ID, TRIP_ID, TYPE, DESCRIPTION, STATUS) 
VALUES (1, 3, 3, 'APPRECIATION', 'Excellent driving and very comfortable seats. Loved the AC!', 'RESOLVED');
INSERT INTO FEEDBACK (FEEDBACK_ID, PASSENGER_ID, TRIP_ID, TYPE, DESCRIPTION, STATUS) 
VALUES (2, 2, 2, 'COMPLAINT', 'Bus was slightly delayed arriving at the stop.', 'REVIEWING');
INSERT INTO FEEDBACK (FEEDBACK_ID, PASSENGER_ID, TRIP_ID, TYPE, DESCRIPTION, STATUS) 
VALUES (3, 1, NULL, 'SUGGESTION', 'Please add more routes to the North.', 'OPEN');

-- Update Sequences
ALTER SEQUENCE SEQ_PASSENGER RESTART WITH 6;
ALTER SEQUENCE SEQ_DRIVER RESTART WITH 4;
ALTER SEQUENCE SEQ_VEHICLE RESTART WITH 5;
ALTER SEQUENCE SEQ_ROUTE RESTART WITH 5;
ALTER SEQUENCE SEQ_TRIP RESTART WITH 5;
ALTER SEQUENCE SEQ_BOOKING RESTART WITH 5;
ALTER SEQUENCE SEQ_PAYMENT RESTART WITH 4;
ALTER SEQUENCE SEQ_MAINTENANCE RESTART WITH 4;
ALTER SEQUENCE SEQ_FEEDBACK RESTART WITH 4;

COMMIT;
