server.port=8082
spring.application.name=vehicle-service
spring.datasource.url=jdbc:oracle:thin:@(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.ap-hyderabad-1.oraclecloud.com))(connect_data=(service_name=g2712e992546d67_smartmove_low.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
spring.datasource.username=ADMIN
spring.datasource.password=Sandanimne@2007
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.format_sql=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
management.endpoints.web.exposure.include=health,info
spring.jpa.properties.hibernate.default_schema=SMARTMOVE
